<script setup lang="ts">
import { ArrowRight, CheckCircle2 } from "lucide-vue-next";
import OutcomeBadge from "@/components/OutcomeBadge.vue";
import IdentityBadge from "@/components/IdentityBadge.vue";
import { overview, sessions } from "@/lib/mock";
import { compactNumber, relativeDate } from "@/lib/format";
</script>

<template><section><div class="mb-7"><h1 class="text-[28px] font-semibold tracking-[-0.025em]">Overview</h1><p class="mt-1.5 max-w-2xl text-sm leading-6 text-zinc-600 dark:text-zinc-400">A compact read on recent memory and deployment activity.</p></div><dl class="grid grid-cols-2 border-y border-zinc-200 md:grid-cols-4 dark:border-zinc-800"><div v-for="item in [{ label: 'Sessions', value: overview.totals.sessions }, { label: 'Requests', value: overview.totals.requests }, { label: 'Input tokens', value: overview.totals.input_tokens }, { label: 'Output tokens', value: overview.totals.output_tokens }]" :key="item.label" class="border-r border-zinc-200 px-5 py-5 first:pl-0 last:border-r-0 dark:border-zinc-800"><dt class="text-xs text-zinc-500">{{ item.label }}</dt><dd class="mt-1 text-xl font-semibold tracking-[-0.025em]">{{ compactNumber(item.value) }}</dd></div></dl><div class="grid gap-10 pt-9 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,.6fr)]"><div><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold">Recent sessions</h2><RouterLink to="/sessions" class="text-xs font-medium text-teal-700 hover:underline dark:text-teal-400">View all</RouterLink></div><div class="border-t border-zinc-200 dark:border-zinc-800"><RouterLink v-for="session in sessions.slice(0, 4)" :key="session.id" :to="`/sessions/${session.id}`" class="group grid gap-3 border-b border-zinc-200 py-4 sm:grid-cols-[minmax(0,1fr)_120px_24px] sm:items-center dark:border-zinc-800"><div><p class="text-sm font-medium text-zinc-900 group-hover:text-teal-700 dark:text-zinc-100 dark:group-hover:text-teal-400">{{ session.intent }}</p><p class="mt-1.5 text-xs text-zinc-500">{{ session.repo }} · {{ relativeDate(session.started_at) }}</p></div><OutcomeBadge :outcome="session.outcome" /><ArrowRight class="hidden size-4 text-zinc-400 sm:block" /></RouterLink></div></div><aside><h2 class="mb-3 text-sm font-semibold">Deployment</h2><div class="border-y border-zinc-200 dark:border-zinc-800"><div v-for="service in ['Worker', 'D1', 'R2']" :key="service" class="flex items-center justify-between border-b border-zinc-200 py-3 last:border-b-0 dark:border-zinc-800"><span class="text-sm text-zinc-700 dark:text-zinc-300">{{ service }}</span><span class="inline-flex items-center gap-1.5 text-xs font-medium text-emerald-700 dark:text-emerald-400"><CheckCircle2 class="size-3.5" />Healthy</span></div></div><h2 class="mb-3 mt-8 text-sm font-semibold">Top models</h2><div class="border-y border-zinc-200 dark:border-zinc-800"><div v-for="model in overview.models" :key="model.name" class="flex items-center justify-between border-b border-zinc-200 py-3 last:border-b-0 dark:border-zinc-800"><IdentityBadge :label="model.name" /><span class="font-mono text-xs text-zinc-500">{{ model.requests }}</span></div></div></aside></div></section></template>
