<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { ArrowLeft } from "lucide-vue-next";
import IdentityBadge from "@/components/IdentityBadge.vue";
import BrandIcon from "@/components/BrandIcon.vue";
import { exchangeById } from "@/lib/mock";
import { outputSpeed, shortDate } from "@/lib/format";

const route = useRoute();
const exchange = computed(() => exchangeById(String(route.params.id)));
const tab = ref<"request" | "response">("request");
</script>

<template><section v-if="exchange"><RouterLink to="/requests" class="mb-6 inline-flex items-center gap-1.5 text-[13px] font-medium text-zinc-500 hover:text-zinc-950 dark:text-zinc-400 dark:hover:text-zinc-100"><ArrowLeft class="size-4" />Requests</RouterLink><div class="border-b border-zinc-200 pb-6 dark:border-zinc-800"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-mono text-xs text-zinc-500">{{ exchange.id }}</p><h1 class="mt-2 flex items-center gap-3 text-[28px] font-semibold tracking-[-0.025em]"><BrandIcon :label="exchange.model" />{{ exchange.model }}</h1><div class="mt-3 flex flex-wrap items-center gap-4"><IdentityBadge :label="exchange.provider" /><IdentityBadge :label="exchange.harness" /><span class="text-xs text-zinc-500">{{ shortDate(exchange.ts) }}</span></div></div><RouterLink :to="`/sessions/${exchange.session_id}`" class="text-[13px] font-medium text-teal-700 hover:underline dark:text-teal-400">View parent session</RouterLink></div></div><dl class="grid grid-cols-2 border-b border-zinc-200 md:grid-cols-5 dark:border-zinc-800"><div v-for="item in [{ label: 'Input', value: exchange.input_tokens.toLocaleString() }, { label: 'Output', value: exchange.output_tokens.toLocaleString() }, { label: 'Latency', value: `${(exchange.latency_ms / 1000).toFixed(2)}s` }, { label: 'Speed', value: outputSpeed(exchange.output_tokens, exchange.latency_ms) }, { label: 'Finish', value: exchange.finish_reason }]" :key="item.label" class="border-r border-zinc-200 px-4 py-5 first:pl-0 last:border-r-0 dark:border-zinc-800"><dt class="text-xs text-zinc-500">{{ item.label }}</dt><dd class="mt-1 font-mono text-xs text-zinc-900 dark:text-zinc-100">{{ item.value }}</dd></div></dl><div class="pt-8"><div class="mb-4 flex gap-5 border-b border-zinc-200 dark:border-zinc-800"><button v-for="name in ['request', 'response'] as const" :key="name" class="relative pb-2.5 text-[13px] font-medium capitalize" :class="tab === name ? 'text-zinc-950 after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 after:bg-zinc-950 dark:text-zinc-100 dark:after:bg-zinc-100' : 'text-zinc-500'" @click="tab = name">{{ name }}</button></div><pre class="max-h-[560px] overflow-auto rounded-[7px] border border-zinc-200 bg-zinc-950 p-5 font-mono text-xs leading-6 text-zinc-200 dark:border-zinc-800"><code>{{ tab === 'request' ? exchange.request : exchange.response }}</code></pre></div></section><section v-else class="py-20 text-center"><h1 class="text-xl font-semibold">Request not found</h1><RouterLink to="/requests" class="mt-3 inline-block text-sm font-medium text-teal-700 dark:text-teal-400">Return to requests</RouterLink></section></template>
