package mimircli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// openCodePlugin routes a harness's OpenRouter traffic through the Mimir
// Worker and tags each exchange with repo, harness, and session identity. The
// machine token is read from ~/.mimir/token at runtime, never written into the
// plugin file.
const openCodePluginTemplate = `import type { Plugin } from "@opencode-ai/plugin";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const WORKER_URL = %q;

// Generated by mimir login. Routes OpenRouter traffic through the Mimir
// Worker so every opencode session is captured in the Mimir dashboard.
export default (async ({ directory }) => {
  const token = readFileSync(join(homedir(), ".mimir", "token"), "utf8").trim();
  const repo = directory.split(/[\\/]/).filter(Boolean).pop() ?? "unknown";
  return {
    config: (cfg) => {
      const providers = (cfg.provider ??= {});
      const openrouter = (providers.openrouter ??= {});
      openrouter.options = {
        ...openrouter.options,
        baseURL: WORKER_URL + "/v1",
        apiKey: token,
      };
    },
    "chat.headers": async (input, output) => {
      output.headers["x-mimir-repo"] = repo;
      output.headers["x-mimir-harness"] = "opencode";
      const sessionId = (input as { sessionID?: string }).sessionID;
      if (sessionId) output.headers["x-mimir-session"] = sessionId;
    },
  };
}) satisfies Plugin;
`

const openCodeEndSessionCommand = `---
description: Summarize, record the outcome, and end the current Mimir session.
---

End the current Mimir session.

1. Use $ARGUMENTS as the required exact session ID. If it is empty, stop and ask for the ID. Never guess an ID.
2. Summarize the completed work and gather concrete evidence such as tests, deployments, pull requests, or commit SHAs.
3. Choose landed, discarded, abandoned, or unresolved based only on that evidence.
4. Call the Mimir MCP session_end tool with the session ID, outcome, concise reason, and evidence.
5. Return the session_end receipt exactly. Do not claim the session was saved unless the receipt says it was saved.
`

// installOpenCodeIntegration writes the Mimir opencode plugin and registers
// the mimir MCP server in opencode.json. Both operations are idempotent and
// preserve any existing opencode configuration.
func installOpenCodeIntegration(home, workerURL string) error {
	configDir := filepath.Join(home, ".config", "opencode")
	if err := os.MkdirAll(filepath.Join(configDir, "plugins"), 0o700); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(configDir, "commands"), 0o700); err != nil {
		return err
	}
	plugin := fmt.Sprintf(openCodePluginTemplate, workerURL)
	if err := os.WriteFile(filepath.Join(configDir, "plugins", "mimir.ts"), []byte(plugin), 0o600); err != nil {
		return fmt.Errorf("writing opencode plugin: %w", err)
	}
	if err := os.WriteFile(filepath.Join(configDir, "commands", "mimir-end-session.md"), []byte(openCodeEndSessionCommand), 0o600); err != nil {
		return fmt.Errorf("writing opencode command: %w", err)
	}
	return upsertOpenCodeMCP(filepath.Join(configDir, "opencode.json"))
}

func upsertOpenCodeMCP(path string) error {
	config := map[string]any{}
	if data, err := os.ReadFile(path); err == nil {
		if err := json.Unmarshal(data, &config); err != nil {
			return fmt.Errorf("reading opencode config: %w", err)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	mcp, _ := config["mcp"].(map[string]any)
	if mcp == nil {
		mcp = map[string]any{}
	}
	mcp["mimir"] = map[string]any{
		"type":    "local",
		"command": []string{"mimir", "serve"},
		"enabled": true,
	}
	config["mcp"] = mcp
	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o600)
}
