<script setup lang="ts">
import { computed } from "vue";
import { ExternalLink, GitCommitHorizontal } from "lucide-vue-next";
import { outcomeCommitEvidence, type GitArtifact, type OutcomeEvent, type OutcomeEvidence } from "@/lib/api";
import { shortDate } from "@/lib/format";
import { commitUrl, externalEvidenceUrl, gitArtifactCommitUrl, gitArtifactProvenance, normalizeRepositoryUrl, outcomeEvidenceArtifact, outcomeUrlMatchesArtifact, shortCommit } from "@/lib/git";
const props = defineProps<{ sessionId: string; artifacts: GitArtifact[]; events: OutcomeEvent[]; evidence: OutcomeEvidence | null; sourceRef?: string | null }>();
const history = computed(() => outcomeCommitEvidence(props.events).map((entry) => ({ ...entry, artifact: outcomeEvidenceArtifact(entry.evidence, props.artifacts) })));
const unmatched = computed(() => history.value.filter((entry) => !entry.artifact));
const outcomeUrl = computed(() => props.evidence?.url ?? (!props.evidence?.commit ? props.evidence?.commit_url : undefined));
const distinctUrl = computed(() => outcomeUrlMatchesArtifact(outcomeUrl.value, props.artifacts) ? null : externalEvidenceUrl(outcomeUrl.value));
const invalidUrl = computed(() => outcomeUrl.value && !externalEvidenceUrl(outcomeUrl.value) ? outcomeUrl.value : null);
const legacy = computed(() => Boolean(props.evidence?.patch || props.evidence?.patch_r2_key));
</script>

<template>
  <div v-if="artifacts.length || unmatched.length || distinctUrl || invalidUrl || evidence?.note || legacy" class="min-w-0 space-y-4">
    <section v-if="artifacts.length" aria-labelledby="changes-heading">
      <div class="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1 border-b border-zinc-200 pb-2 dark:border-zinc-800"><h2 id="changes-heading" class="text-sm font-semibold">Captured commits <span class="font-mono text-xs font-normal text-zinc-600 dark:text-zinc-400">{{ artifacts.length }}</span></h2><RouterLink to="/commits" class="text-xs text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-teal-400">Repository timeline</RouterLink></div>
      <p class="py-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">Only saved captures include a patch. A local commit does not establish a push or landing.</p>
      <ol v-if="artifacts.length" class="divide-y divide-zinc-200 border-y border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800">
        <li v-for="artifact in artifacts" :key="artifact.commit_sha" class="py-3">
          <div class="flex min-w-0 items-start gap-2.5"><GitCommitHorizontal class="mt-0.5 size-4 shrink-0 text-zinc-600 dark:text-zinc-400" aria-hidden="true" /><div class="min-w-0 flex-1"><div class="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1"><h3 class="break-words text-[13px] font-medium leading-5">{{ artifact.subject || 'Untitled commit' }}</h3><span v-if="artifact.committed_at" class="text-xs text-zinc-600 dark:text-zinc-400">{{ shortDate(artifact.committed_at) }}</span></div><div class="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs"><code :title="artifact.commit_sha">{{ shortCommit(artifact.commit_sha) }}</code><span v-if="artifact.ref" class="break-all text-zinc-600 dark:text-zinc-400">{{ artifact.ref }}</span><span class="text-zinc-600 dark:text-zinc-400">{{ artifact.patch_files }} files <span class="font-mono text-emerald-700 dark:text-emerald-400">+{{ artifact.patch_additions }}</span> <span class="font-mono text-red-700 dark:text-red-400">−{{ artifact.patch_deletions }}</span></span><span :class="artifact.capture_status === 'failed' ? 'text-red-700 dark:text-red-400' : 'text-zinc-600 dark:text-zinc-400'">{{ artifact.capture_status === 'saved' ? 'Patch saved' : artifact.capture_status === 'failed' ? 'Capture failed' : 'Capture pending' }}</span></div></div></div>
          <div class="mt-2 flex flex-wrap items-center gap-4 text-xs">
            <RouterLink v-if="artifact.capture_status === 'saved'" :to="{ name: 'session-artifact-diff', params: { id: sessionId, commit: artifact.commit_sha } }" class="font-medium text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-teal-400">View changes</RouterLink>
            <span v-else-if="artifact.failure_code" class="break-words text-red-700 dark:text-red-400">Capture failed: {{ artifact.failure_code }}</span>
            <a v-if="gitArtifactCommitUrl(artifact)" :href="gitArtifactCommitUrl(artifact)!" target="_blank" rel="noreferrer noopener" class="text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-teal-400">Remote commit <ExternalLink class="inline size-3" /><span class="sr-only">(new tab)</span></a>
            <details class="min-w-0 basis-full"><summary class="cursor-pointer text-zinc-600 focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-zinc-400">Capture details</summary><dl class="mt-2 grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-1 break-words text-xs"><dt>Full SHA</dt><dd class="break-all font-mono">{{ artifact.commit_sha }}</dd><dt>Repository</dt><dd class="break-all">{{ normalizeRepositoryUrl(artifact.repository_url) || 'Unknown repository' }}</dd><dt>Source</dt><dd>{{ gitArtifactProvenance(artifact.provenance).label }} ({{ artifact.provenance }})</dd><dt>Accepted</dt><dd>{{ shortDate(artifact.accepted_at) }}</dd><template v-if="artifact.saved_at"><dt>Saved</dt><dd>{{ shortDate(artifact.saved_at) }}</dd></template><template v-if="artifact.failed_at"><dt>Failed</dt><dd>{{ shortDate(artifact.failed_at) }}</dd></template><dt>Digest</dt><dd class="break-all font-mono">{{ artifact.patch_sha256 }}</dd><dt>Bytes</dt><dd>{{ artifact.patch_bytes.toLocaleString() }}</dd></dl><div v-for="entry in history.filter(item => item.artifact?.commit_sha === artifact.commit_sha)" :key="entry.event.id" class="mt-2 break-words border-t border-zinc-200 pt-2 dark:border-zinc-800"><p>Separate outcome record: <span class="capitalize">{{ entry.event.outcome }}</span> · {{ shortDate(entry.event.created_at) }} · {{ entry.event.source }}</p><p v-if="entry.event.reason" class="mt-1">{{ entry.event.reason }}</p><p v-if="entry.evidence.note" class="mt-1">{{ entry.evidence.note }}</p></div></details>
          </div>
        </li>
      </ol>
    </section>
    <section v-if="unmatched.length || distinctUrl || invalidUrl || evidence?.note || legacy" aria-labelledby="outcome-evidence-heading">
      <h2 id="outcome-evidence-heading" class="border-b border-zinc-200 pb-2.5 text-sm font-semibold dark:border-zinc-800">Separate outcome evidence</h2>
      <p class="py-2 text-xs text-zinc-600 dark:text-zinc-400">Recorded outcome claims are not patch capture receipts.</p>
      <ol class="divide-y divide-zinc-200 dark:divide-zinc-800"><li v-for="entry in unmatched" :key="entry.event.id" class="py-2 text-xs"><div class="flex flex-wrap gap-x-3 gap-y-1"><a v-if="commitUrl(entry.evidence)" :href="commitUrl(entry.evidence)!" target="_blank" rel="noreferrer noopener" class="font-mono text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-teal-400">{{ shortCommit(entry.evidence.commit) }} <ExternalLink class="inline size-3" /></a><code v-else>{{ shortCommit(entry.evidence.commit) }}</code><span class="capitalize">{{ entry.event.outcome }}</span><span class="text-zinc-600 dark:text-zinc-400">{{ shortDate(entry.event.created_at) }} · {{ entry.event.source }}</span><span v-if="entry.evidence.ref || sourceRef" class="break-all text-zinc-600 dark:text-zinc-400">{{ entry.evidence.ref || sourceRef }}</span></div><p v-if="entry.event.reason" class="mt-1 break-words leading-5">{{ entry.event.reason }}</p><p class="mt-1 text-zinc-600 dark:text-zinc-400">No matching independent patch capture.</p></li></ol>
      <p v-if="distinctUrl" class="py-2 text-xs"><a :href="distinctUrl" target="_blank" rel="noreferrer noopener" class="break-all text-teal-700 hover:underline dark:text-teal-400">{{ distinctUrl }} <ExternalLink class="inline size-3" /></a></p>
      <p v-if="invalidUrl" class="py-2 text-xs text-zinc-600 dark:text-zinc-400">Recorded link is not a safe web URL: <code class="break-all">{{ invalidUrl }}</code></p>
      <p v-if="evidence?.note" class="break-words py-2 text-xs leading-5 text-zinc-600 dark:text-zinc-400">{{ evidence.note }}</p>
      <RouterLink v-if="legacy" :to="{ name: 'session-diff', params: { id: sessionId } }" class="mt-2 inline-block text-xs text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-teal-600 dark:text-teal-400">Open complete legacy patch</RouterLink>
    </section>
  </div>
</template>
